version: '3.3'

services:

  db:

    image: postgres

    restart: always
    
    ports:

      - "5432:5432"
    
    environment:
    
      - DATABASE_HOST=127.0.0.1 

      - POSTGRES_USER=postgres

      - POSTGRES_PASSWORD=1234

      - POSTGRES_DB=dbbanco

    container_name: postgres-db

    volumes:

      - ./pgdata:/var/lib/postgresql/data

  pgadmin:

    image: dpage/pgadmin4

    restart: always

    container_name: nest-pgadmin4

    environment:

      - PGADMIN_DEFAULT_EMAIL=postgres

      - PGADMIN_DEFAULT_PASSWORD=1234

      - PGADMIN_LISTEN_PORT=5432

    ports:

      - "81:81"

    volumes:

      - ./pgadmin-data:/var/lib/pgadmin

    depends_on:

      - db
